ROLE_SYNONYMS: dict[str, list[str]] = {
    "visual_merchandiser": [
        "visual merchandiser",
        "visual merchandising",
        "retail merchandiser",
        "store merchandiser",
        "merchandising specialist",
        "brand merchandiser",
        "planogram",
        "retail presentation",
        "in-store marketing",
    ],
    "data_analyst": [
        "data analyst",
        "analytics analyst",
        "reporting analyst",
        "bi analyst",
        "business intelligence analyst",
        "data reporting",
        "insights analyst",
        "dashboarding",
    ],
    "business_analyst": [
        "business analyst",
        "ba",
        "systems analyst",
        "process analyst",
        "requirements analyst",
        "functional analyst",
        "operations analyst",
    ],
    "prompt_engineer": [
        "prompt engineer",
        "llm prompt engineer",
        "ai prompt specialist",
        "prompt designer",
        "llm analyst",
        "ai conversation designer",
        "prompt/llm evaluation",
    ],
    "product_analyst": [
        "product analyst",
        "product analytics",
        "growth analyst",
        "product data analyst",
        "experimentation analyst",
        "product insights",
    ],
    "quantitative_research_analyst": [
        "quantitative research analyst",
        "quant analyst",
        "quantitative analyst",
        "research analyst (quant)",
        "statistical analyst",
        "modeling analyst",
        "optimization",
    ],
    "ai_workflow_developer": [
        "ai workflow developer",
        "ai automation specialist",
        "automation specialist",
        "ai automation",
        "workflow automation",
        "ai ops",
        "llm workflows",
        "zapier",
        "make",
        "n8n",
        "langchain workflows",
        "rpa",
        "agent workflows",
    ],
}

SKILLS_DICTIONARY = [
    "sql",
    "python",
    "excel",
    "tableau",
    "power bi",
    "looker",
    "statistics",
    "a/b testing",
    "dashboard",
    "etl",
    "api",
    "jira",
    "confluence",
    "requirements gathering",
    "stakeholder management",
    "planogram",
    "merchandising",
    "retail presentation",
    "n8n",
    "zapier",
    "make",
    "langchain",
    "prompt engineering",
    "llm evaluation",
    "r",
    "pandas",
    "numpy",
    "scikit-learn",
    "customer service",
    "sales",
    "salesforce",
    "crm",
    "cold calling",
    "lead generation",
    "account management",
    "retail",
    "cash handling",
    "point of sale",
    "pos",
    "inventory",
    "stocking",
    "merchandising",
    "planogram",
    "warehouse",
    "forklift",
    "shipping",
    "receiving",
    "fulfillment",
    "manufacturing",
    "assembly",
    "quality control",
    "operations",
    "scheduling",
    "training",
    "coaching",
    "team leadership",
    "communication",
    "problem solving",
    "project management",
    "reporting",
    "data entry",
    "microsoft office",
    "word",
    "powerpoint",
    "google sheets",
    "google workspace",
    "food service",
    "kitchen",
    "cooking",
    "prep",
    "sanitation",
    "safety",
    "delivery",
    "driving",
    "cdl",
    "construction",
    "labor",
    "market research",
    "quantitative analysis",
    "data analysis",
    "data analytics",
    "business development",
    "account management",
    "customer engagement",
    "customer satisfaction",
    "risk management",
    "trading",
    "strategy",
    "leadership",
    "coaching",
    "technical analysis",
    "volatility analysis",
    "trend analysis",
    "rust",
    "node.js",
    "nodejs",
    "small business",
]

# Resume-first ranking: role/skills dominate, location/pay are secondary.
DEFAULT_WEIGHTS = {
    "role": 0.32,
    "skills": 0.36,
    "distance": 0.14,
    "salary": 0.08,
    "freshness": 0.06,
    "source": 0.04,
}

# Recommendation blend: resume fit dominates, hobbies add preference tuning.
RECOMMENDATION_BLEND = {
    "resume": 0.92,
    "hobbies": 0.08,
}

SCORE_TUNING_MODES = {
    "strict": {
        "interview_multiplier": 0.92,
        "compatibility_multiplier": 0.94,
        "entry_boost_cap": 0.08,
        "senior_penalty_cap": 0.35,
        "interview_bonus": -0.03,
    },
    "balanced": {
        "interview_multiplier": 1.0,
        "compatibility_multiplier": 1.0,
        "entry_boost_cap": 0.12,
        "senior_penalty_cap": 0.30,
        "interview_bonus": 0.0,
    },
    "aggressive": {
        "interview_multiplier": 1.08,
        "compatibility_multiplier": 1.06,
        "entry_boost_cap": 0.18,
        "senior_penalty_cap": 0.25,
        "interview_bonus": 0.06,
    },
}

# Skill families used to credit transferable experience beyond exact keyword matches.
TRANSFERABLE_SKILL_GROUPS: dict[str, list[str]] = {
    "analysis_reporting": [
        "data analysis",
        "data analytics",
        "analytics",
        "reporting",
        "dashboard",
        "tableau",
        "power bi",
        "excel",
        "sql",
        "statistics",
    ],
    "operations_execution": [
        "operations",
        "scheduling",
        "inventory",
        "stocking",
        "quality control",
        "shipping",
        "receiving",
        "fulfillment",
        "warehouse",
        "manufacturing",
        "assembly",
        "labor",
    ],
    "customer_sales": [
        "customer service",
        "customer satisfaction",
        "customer engagement",
        "sales",
        "salesforce",
        "crm",
        "cold calling",
        "lead generation",
        "business development",
        "account management",
        "retail",
        "pos",
        "point of sale",
        "cash handling",
    ],
    "people_leadership": [
        "communication",
        "training",
        "coaching",
        "team leadership",
        "leadership",
        "stakeholder management",
        "project management",
        "problem solving",
    ],
    "digital_automation": [
        "python",
        "api",
        "etl",
        "zapier",
        "n8n",
        "make",
        "langchain",
        "prompt engineering",
        "llm evaluation",
        "node.js",
        "nodejs",
    ],
}

# Hobby-to-job signals are private profile preference signals.
# They should never be included in employer-facing materials.
HOBBY_JOB_SIGNALS: dict[str, list[str]] = {
    "cryptocurrency": [
        "crypto",
        "cryptocurrency",
        "blockchain",
        "web3",
        "defi",
        "digital asset",
        "token",
        "trading",
        "fintech",
    ],
    "rock climbing": [
        "outdoor",
        "fitness",
        "adventure",
        "recreation",
        "guide",
        "coach",
    ],
    "video games": [
        "game",
        "gaming",
        "esports",
        "unity",
        "unreal",
        "player support",
        "community manager",
        "qa tester",
    ],
    "smoking marijuana": [
        "cannabis",
        "dispensary",
        "budtender",
        "cultivation",
        "hemp",
    ],
    "pokemon": [
        "trading card",
        "tcg",
        "collectibles",
        "toy",
        "hobby shop",
        "game store",
        "retail",
    ],
    "working out/staying active": [
        "fitness",
        "gym",
        "trainer",
        "wellness",
        "health club",
        "coach",
        "physical",
    ],
    "taking care of plants": [
        "plant",
        "greenhouse",
        "nursery",
        "horticulture",
        "landscaping",
        "garden",
        "agriculture",
    ],
    "vibecoding applications": [
        "software",
        "developer",
        "coding",
        "programming",
        "automation",
        "ai",
        "llm",
        "app",
        "web",
    ],
    "thrifting": [
        "retail",
        "resale",
        "consignment",
        "ecommerce",
        "merchandise",
        "inventory",
    ],
    "driving": [
        "driver",
        "delivery",
        "courier",
        "transport",
        "logistics",
        "fleet",
        "route",
        "cdl",
    ],
    "music": [
        "music",
        "audio",
        "sound",
        "media",
        "production",
        "creative",
        "entertainment",
    ],
}

ENTRY_LEVEL_TITLE_TERMS = [
    "entry level",
    "junior",
    "jr",
    "associate",
    "assistant",
    "trainee",
    "intern",
    "apprentice",
]

SENIOR_TITLE_TERMS = [
    "senior",
    "sr",
    "staff",
    "lead",
    "manager",
    "director",
    "principal",
    "head of",
    "vp",
    "vice president",
    "chief",
]

SOURCE_TRUST = {
    "greenhouse": 1.0,
    "lever": 1.0,
    "company_board": 0.95,
    "rss": 0.75,
    "adzuna": 0.7,
    "manual": 0.8,
    "csv": 0.65,
}

# Public board tokens/slugs only (legal to query via public APIs).
AGGRESSIVE_GREENHOUSE_TOKENS = [
    "openai",
    "stripe",
    "twilio",
    "datadog",
    "doordash",
    "coinbase",
    "airbnb",
    "reddit",
    "robinhood",
    "instacart",
    "lyft",
    "plaid",
    "brex",
    "discord",
    "canva",
    "hubspot",
    "asana",
    "squareup",
    "affirm",
    "cloudflare",
    "snowflake",
    "riotgames",
    "pinterest",
    "shopify",
    "palantir",
    "dropbox",
    "zillow",
    "coinlist",
    "wayfair",
    "newegg",
    "instabase",
    "tempus",
    "zocdoc",
]

AGGRESSIVE_LEVER_SLUGS = [
    "atlassian",
    "gusto",
    "mongodb",
    "rippling",
    "figma",
    "notion",
    "segment",
    "samsara",
    "reddit",
    "coinbase",
    "canva",
    "brex",
    "doordash",
    "scale-ai",
    "upstart",
    "coursera",
    "mapbox",
    "planet",
    "heap",
    "benchling",
]

AGGRESSIVE_MUSE_CATEGORIES = [
    "Business Operations",
    "Sales",
    "Data and Analytics",
    "Customer Service",
    "Retail",
    "Manufacturing and Warehouse",
    "Food and Hospitality",
]

# Contiguous U.S. states (lower 48) for nationwide recommendation scans.
CONTIGUOUS_US_STATES = [
    "Alabama",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
]

US_STATE_ABBREV_TO_NAME = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
    "DC": "District of Columbia",
}

US_STATE_NAME_TO_ABBREV = {name.upper(): code for code, name in US_STATE_ABBREV_TO_NAME.items()}
